- hosts: adb-server
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no

- include: preparation.yml
- include: mysql.yml
- include: php.yml
- include: apache.yml
- include: git-clone.yml
- include: composer.yml
- include: make-files.yml

