---

- name: Install apache2
  apt: name=apache2 state=present

- name: Restart apache2
  service: name=apache2 state=restarted

- name: Clean html path
  shell: /bin/rm -rf /var/www/html

- name: Create project directory and set its permissions
  file:
    path: /var/www/html/adb_webapp
    state: directory
    owner: root
    group: root
    mode: 0777

- debug: msg="Apache has been installed"
